version: "3.9"

services:
  agent:
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ee:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      labels:
        # WebUI
        - traefik.enable=true
        - traefik.http.routers.portainer.rule=Host(`portainer.home`)
        - traefik.http.routers.portainer.entrypoints=web
        - traefik.http.services.portainer.loadbalancer.server.port=9000
        - traefik.http.routers.portainer.service=portainer

        # Edge
        - traefik.http.routers.portaineredge.rule=Host(`portaineredge.home`)
        - traefik.http.routers.portaineredge.entrypoints=web
        - traefik.http.services.portaineredge.loadbalancer.server.port=8000
        - traefik.http.routers.portaineredge.service=portaineredge
      placement:
        constraints:
          - node.role == manager
          - node.hostname == merel

networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
